### ISSUE TITLE
App can't turn off light (LG G2, Android 5.0.2)

### ISSUE THREAD

**Issue by chreekat** [SimpleMobileTools/Simple-Flashlight#4] opened 2016-07-16 09:36 UTC
Clicking the widget multiple times, the light just stays on.

**Comment by tibbi** [comment] 2016-07-16 09:56
hello, what device and Android version do you have?

**Comment by chreekat** [comment] 2016-07-16 09:59
Let's see, it's an LG G2 (LG-D801), Android 5.0.2. Hope that helps!

**Comment by sc0repi0** [comment] 2016-07-18 20:46
I can confirm this behaviour with the app itself.

LG G2 (LG.D802), Android 5.0.2

**Comment by tibbi** [comment] 2016-07-20 18:05
Was the light turned on with the widget? Does the icon change on clicking?

**Comment by chreekat** [comment] 2016-07-20 18:51
Yes and yes.

**Comment by sc0repi0** [comment] 2016-07-20 18:57
If it helps: I don't use the widget, I'm only starting the app itself. The light switches on, but the button will not kill it again. I have to kill the app via task manager.

@tibbi Thanks for working on it!

**Comment by tibbi** [comment] 2016-07-20 19:07
ok thanks for the responses. The problem is that the Camera API itself is terrible and things can differ per manufacturer and OS version too :/ Im testing the apps on multiple devices with different android versions, but I just cannot reproduce this one on any of them. Cannot even use an emulator as it's related to a flashlight and the icon itself changes properly...

**Comment by chreekat** [comment] 2016-07-20 20:12
Haha doh. :P Unfortunately I've never done any Android development and
don't have time now to get set up to dig into it!

**Comment by sc0repi0** [comment] 2016-07-20 21:01
Dont' worry @tibbi 

I cannot help either, don't have the expertise, sorry. I just wanted to get in line and communicate the problem. Will still use the app though, it's still convenient to use it.

**Comment by chreekat** [comment] 2016-07-21 18:51
I actually have the same general problem that @sc0repi0 mentioned, where the only way to turn off the light is by killing the app. :P I'll make the issue more specific; maybe someone else will be able to come along and poke at it.

**Comment by tibbi** [comment] 2016-07-25 21:05
can you guys recheck with 1.11? Ive made a change there which might be not related to this one, but who knows wth is causing it...

**Comment by chreekat** [comment] 2016-07-26 10:50
I installed it via F-Droid. Have you pushed a new version there? (I don't know how any of that works.)

**Comment by tibbi** [comment] 2016-07-26 11:27
they are updating it themselves by some script every day or so, just go to About and check the version at the bottom

**Comment by sc0repi0** [comment] 2016-07-26 21:50
The app works as intended, thank you very much! I just updated it from Play store (also had it installed via F-Droid). I cannot say anything about the widget though, since my launcher simple does not let me have widgets.

**Comment by sc0repi0** [comment] 2016-07-26 21:51
The app works as intended, thank you very much! I just updated it from Play store (also had it installed via F-Droid). I cannot say anything about the widget though, since my launcher simple does not let me have widgets.

**Comment by tibbi** [comment] 2016-07-26 22:21
heh ok, thanks for the testing :) Ill close it fast while it works.

**Closed by tibbi** 2016-07-26 22:21 UTC
Labels: bug

**Comment by chreekat** [comment] 2016-07-29 03:32
Yup, f droid just updated the app to 1.11 and now it works properly for me,
too. :)

On Jul 21, 2016 12:01 AM, "sc0repi0" <notifications@github.com> wrote:

Dont' worry @tibbi <https://github.com/tibbi>

I cannot help either, don't have the expertise, sorry. I just wanted to get
in line and communicate the problem. Will still use the app though, it's
still convenient to use it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SimpleMobileTools/Simple-Flashlight/issues/4#issuecomment-234081827>,
or mute the thread
