### ISSUE TITLE
MainActivity crash on Huawei Honor Marshmallow

### ISSUE THREAD

**Issue by YoungNFoolish** [SimpleMobileTools/Simple-Flashlight#8] opened 2016-08-01 21:36 UTC
hi, i compiled the app and tried to run it in debug mode but on my honor android 6 the main app opens for a little while and suddenly crashes!
please fix it.

**Comment by tibbi** [comment] 2016-08-02 06:42
and what does the crashdump say?

**Comment by YoungNFoolish** [comment] 2016-08-02 10:20
it's logcat report:
`
08-02 14:45:34.270  3082  4741 I wm_stack_created: [3,0,0,0,0]
08-02 14:45:34.275  3082  4741 I am_home_stack_moved: [0,0,3,3,startingNewTask]
08-02 14:45:34.275  3082  4741 I am_create_task: [0,27]
08-02 14:45:34.275  3082  4741 I am_create_activity: [0,77325025,27,com.simplemobiletools.flashlight/.activities.MainActivity,android.intent.action.MAIN,NULL,NULL,270532608]
08-02 14:45:34.276  3082  4741 I wm_task_created: [27,3]
08-02 14:45:34.276  3082  4741 I wm_task_moved: [27,1,0]
08-02 14:45:34.278  3082  4741 I am_pause_activity: [0,257804943,com.huawei.android.launcher/.Launcher]
08-02 14:45:34.280  3082  4741 I am_home_stack_moved: [0,0,3,3,startedActivity setFocusedActivity]
08-02 14:45:34.282  3082  4741 I wm_task_moved: [27,1,0]
08-02 14:45:34.284  3082  4741 I am_focused_activity: [0,com.simplemobiletools.flashlight/.activities.MainActivity]
08-02 14:45:34.289  3966  3966 I am_on_paused_called: [0,com.huawei.android.launcher.Launcher]
08-02 14:45:34.302  3082  3093 I am_proc_start: [0,10696,10027,com.simplemobiletools.flashlight,activity,com.simplemobiletools.flashlight/.activities.MainActivity]
08-02 14:45:34.345  3082  4711 I am_proc_bound: [0,10696,com.simplemobiletools.flashlight]
08-02 14:45:34.348  3082  4711 I am_restart_activity: [0,77325025,27,com.simplemobiletools.flashlight/.activities.MainActivity]
08-02 14:45:34.355  3082  4711 I am_focused_activity: [0,com.simplemobiletools.flashlight/.activities.MainActivity]
08-02 14:45:34.600  3082  4710 I am_crash: [10696,0,com.simplemobiletools.flashlight,952680006,java.lang.IllegalArgumentException,the camera device doesn't have a flash unit.,CameraManager.java,889]
08-02 14:45:34.601  3082  4710 I am_finish_activity: [0,77325025,27,com.simplemobiletools.flashlight/.activities.MainActivity,force-crash]
08-02 14:45:34.625  3082  4710 I am_pause_activity: [0,77325025,com.simplemobiletools.flashlight/.activities.MainActivity]
08-02 14:45:34.633  3082  3837 I am_create_service: [0,219594218,.DropBoxEntryAddedService,10010,4378]
08-02 14:45:34.650  3082  3984 I am_create_service: [0,114443857,.PhenotypeService,10010,3819]
08-02 14:45:34.651  2415  2415 I sf_frame_dur: [com.huawei.android.launcher/com.huawei.android.launcher.Launcher,0,1,0,1,1,0,1]
08-02 14:45:34.654  3082  4710 I am_create_service: [0,182475556,.LockboxBrokerService,10010,3819]
08-02 14:45:34.660  3082  3092 I am_create_service: [0,187107411,.UsageReportingService,10010,3819]
08-02 14:45:34.687  3082  3782 I am_destroy_service: [0,219594218,4378]
08-02 14:45:34.717  3082  4710 I am_proc_died: [0,10696,com.simplemobiletools.flashlight]
08-02 14:45:34.718  3082  4710 I am_focused_activity: [-1,NULL]
08-02 14:45:34.718  3082  4710 I wm_task_removed: [27,removeTask]
08-02 14:45:34.719  3082  4710 I am_home_stack_moved: [0,1,0,0,appDied leftTaskHistoryEmpty]
08-02 14:45:34.719  3082  4710 I wm_stack_removed: 3
08-02 14:45:34.721  3082  4710 I am_resume_activity: [0,257804943,23,com.huawei.android.launcher/.Launcher]
08-02 14:45:34.725  3966  3966 I am_on_resume_called: [0,com.huawei.android.launcher.Launcher]
08-02 14:45:34.726  3082  4710 I wm_task_moved: [23,1,0]
08-02 14:45:34.731  3082  4710 I am_focused_activity: [0,com.huawei.android.launcher/.Launcher]
08-02 14:45:34.770  3082  3984 I am_create_service: [0,219141807,.WeatherService,10064,10023]
08-02 14:45:34.795  3082  4741 I am_destroy_service: [0,219141807,10023]
08-02 14:45:35.007  3082  3984 I am_create_service: [0,226618044,.TransactionService,10060,9389]
`

**Comment by YoungNFoolish** [comment] 2016-08-02 10:24
The interesting thing is that if i remove the marshmallow-specific codes and compile the project with api 22 every things work properly!
FYI, my testing phone is Honor 4c android 6.

**Comment by tibbi** [comment] 2016-08-02 10:32
Does your device have a flash at all? Looks like it doesnt, so normally you wouldnt even be able to install the app, just building it yourself.

**Comment by YoungNFoolish** [comment] 2016-08-02 12:30
Yes it does and even the flash turns on/off by the widget.

**Comment by tibbi** [comment] 2016-08-02 17:25
I cannot reproduce it. Even if I run it on a device without flash I just properly get a toast with the error message. Do you have the latest version? There was an issue with such devices, but it was fixed with this line https://github.com/SimpleMobileTools/Simple-Flashlight/blob/6145043c8aad5365addf88126829a5f343eab803/app/src/main/java/com/simplemobiletools/flashlight/MarshmallowCamera.java#L26

**Comment by tibbi** [comment] 2016-09-25 21:50
can you retest with 1.19 please?

**Comment by YoungNFoolish** [comment] 2016-09-26 17:10
Yes and i did! The same problem... :(
The app opens and turns the flash on for a little while then it suddenly crashes!

**Comment by tibbi** [comment] 2017-11-06 11:24
this is old, should be fixed in the next version 2.0.0

**Closed by tibbi** 2017-11-06 11:24 UTC
Labels: bug
